### ISSUE TITLE
BulkSMSBD

### ISSUE THREAD

**Issue by mhmamun6316** [iqbalhasandev/laravel-bulksmsbd#1]
App\Http\Controllers\BulkSMSBD not found 
Please provide what is need to write in the begining of controller for use Bulksmsbd::send

**Comment by iqbalhasandev** [comment]
I'm sorry to say I couldn't update the package. Because I didn't get any help from [bulksmsbd](https://www.bulksmsbd.com/).  So I stopped working on this package. However, I think I need to update my package, but since my exam is running, I can't update this package until my exam is over. Until then, I am sorry I couldn't give any support.

I'm sorry for that

**Comment by mhmamun6316** [comment]
Thank you for your response. 
I solved the problem comparing other service providers documentation..

**Comment by iqbalhasandev** [comment]
If you currently want to use my package.
Use this class at the top of the controller

`use iqbalhasandev \ bulksmsbd \ Classes \ BulkSMSBD;`


Example:
```
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use iqbalhasandev\bulksmsbd\Classes\BulkSMSBD;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {

        $number = 01712345678;
        $message = 'this is a demo Example form Laravel bulksmsBD Package.';
        BulkSMSBD::send($number, $message);

        
        return view('home');
    }
}

```
